return {}
-- return {
--   "zbirenbaum/copilot-cmp",
--   config = function()
--     local lspkind = require("lspkind")
--     require("copilot_cmp").setup({
--       formatting = {
--         format = lspkind.cmp_format({
--           mode = "symbol",
--           max_width = 50,
--           symbol_map = { Copilot = "" },
--         }),
--       },
--     })
--   end,
-- }
