return {
  -- "neovim/nvim-lspconfig",
  -- opts = {
  --   -- make sure mason installs the server
  --   servers = {
  --     tsserver = {
  --       enabled = false,
  --     },
  --     vtsls = {
  --       settings = {
  --         complete_function_calls = true,
  --         vtsls = {
  --           enableMoveToFileCodeAction = true,
  --           experimental = {
  --             completion = {
  --               enableServerSideFuzzyMatch = true,
  --             },
  --           },
  --         },
  --         typescript = {
  --           updateImportsOnFileMove = { enabled = "always" },
  --           suggest = {
  --             completeFunctionCalls = true,
  --           },
  --           inlayHints = {
  --             enumMemberValues = { enabled = true },
  --             functionLikeReturnTypes = { enabled = true },
  --             parameterNames = { enabled = "literals" },
  --             parameterTypes = { enabled = true ,
  --             propertyDeclarationTypes = { enabled = true },
  --             variableTypes = { enabled = false },
  --           },
  --         },
  --         javascript = {
  --           updateImportsOnFileMove = { enabled = "always" },
  --           suggest = {
  --             completeFunctionCalls = true,
  --           },
  --           inlayHints = {
  --             enumMemberValues = { enabled = false },
  --             functionLikeReturnTypes = { enabled = false },
  --             parameterNames = { enabled = false },
  --             parameterTypes = { enabled = false },
  --             propertyDeclarationTypes = { enabled = false },
  --             variableTypes = { enabled = false },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
